"""contact emails table

Revision ID: 5d8f3b095695
Revises: 12f1aeea7371
Create Date: 2024-09-09 17:52:53.526566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8f3b095695'
down_revision = '12f1aeea7371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_emails_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_emails_email'))

    op.drop_table('contact_emails')
    # ### end Alembic commands ###
